[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity0"
[network]
port = 30303
min_peers = 1
discovery = false
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[mining]
# reseal_on_txs = "none"
usd_per_tx = "0"
[websockets]
port = 8546
[misc]
logging = "info"
log_file = "/var/log/parity.log"
color = true
[account]
password = ["node.pwd"]
